apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocpnode-emiy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocpnode-emiy
    app.kubernetes.io/part-of: test4
  name: ocpnode-emiy
  namespace: utherp0-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: ocpnode-emiy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: ocpnode-emiy
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:utherp0-tenant-ocpnode-emiy
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
