apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocpnode-emiy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocpnode-emiy
    app.kubernetes.io/part-of: test4
  name: ocpnode-emiy
  namespace: utherp0-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: ocpnode-emiy
    weight: null
status: {}
