apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ocpnode-emiy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocpnode-emiy
    app.kubernetes.io/part-of: test4
  name: ocpnode-emiy
  namespace: utherp0-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: ocpnode-emiy
status:
  loadBalancer: {}
